# Generated by Django 2.1.5 on 2019-02-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_word', models.CharField(max_length=50, verbose_name='input_word')),
                ('output_word', models.CharField(max_length=50, verbose_name='input_word')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
    ]
