# Generated by Django 2.1.5 on 2019-02-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translatetable',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma_tarihi'),
        ),
        migrations.AlterField(
            model_name='translatetable',
            name='output_word',
            field=models.CharField(max_length=50, verbose_name='output_word'),
        ),
    ]
